# GFLOPs  GMACs   Params.(M)
#  0.91    0.45    3.473
# Throughput (ins./s):4212.155113370464

model:
  NAME: BaseCls
  encoder_args:
    NAME: MedPTFeatureExtractor
    in_channels: 4
  cls_args:
    NAME: ClsHead
    num_classes: 10
    in_channels: 1024
    mlps: [512,256]
    norm_args:
      norm: 'bn1d'
    is_mil: True
    pooling: conjunctive

dataset:
  common:
    name: Drugs
    data_dir: /media/mvries/2ndDisk/Datasets/SingleCellFromNathan_17122021/
    train:
      split: train
    val:
      split: val
      num_points: 1024

batch_size: 16
val_batch_size: 32
seed: 42
num_classes: 10
classes: [0, 1, 3, 4, 5, 6, 7, 8, 9]