# GFLOPs  GMACs   Params.(M)
#  0.91    0.45    3.473
# Throughput (ins./s):4212.155113370464 

model:
  NAME: BaseCls
  encoder_args:
    NAME: PointNetEncoder
    in_channels: 4
  cls_args:
    NAME: ClsHead
    num_classes: 15
    in_channels: 1024
    mlps: [512,256]
    norm_args:
      norm: 'bn1d'
    is_mil: True
    pooling: 'additive'

dataset:
  common:
    data_dir: /mnt/nvme0n1/Datasets/ScanObjectNN/data/h5_files/main_split/
    train:
      split: train
    val:
      split: val
      num_points: 1024

batch_size: 32
val_batch_size: 32