# GFLOPs  GMACs   Params.(M)
#  1.64    0.81    1.374

# C=64
# GFLOPs  GMACs   Params.(M)
#  6.49    3.23    4.523
# Throughput (ins./s): 2032.9397323777052

model:
  NAME: BaseCls
  encoder_args:
    NAME: PointNextEncoder
    blocks: [1, 1, 1, 1, 1, 1]
    strides: [1, 2, 2, 2, 2, 1]
    width: 32
    in_channels: 3 
    radius: 0.15
    radius_scaling: 1.5
    sa_layers: 2
    sa_use_res: True
    nsample: 32
    expansion: 4
    aggr_args:
      feature_type: 'dp_fj'
      reduction: 'max'
    group_args:
      NAME: 'ballquery'
      normalize_dp: True
    conv_args:
      order: conv-norm-act
    act_args:
      act: 'relu'
    norm_args:
      norm: 'bn'
    is_mil: False
  cls_args: 
    NAME: ClsHead
    num_classes: 3
    mlps: [512, 256]
    norm_args: 
      norm: 'bn1d'
    is_mil: False

dataset:
  common:
    NAME: Drugs
    data_dir: /mnt/nvme0n1/Datasets/SingleCellFromNathan_17122021/


seed: 42
num_classes: 3
classes: [0, 1, 2]

sched: cosine
epochs: 100
t_max: 100
min_lr: 0.005
warmup_epochs: 0  # Later change to 10?

criterion_args:
  NAME: SmoothCrossEntropy
  label_smoothing: 0.2

datatransforms:
  train: [PointsToTensor, PointCloudScaleAndTranslate]
  vote: [PointCloudScaleAndTranslate]
  val: [PointsToTensor]
  kwargs:
    shift: [0.2, 0.2, 0.2]

batch_size: 32
val_batch_size: 64